apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: false
  artifacts:
    - image: aditya43/service-01
      context: ../../service-01
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: aditya43/service02
      context: ../../service02
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .