apiVersion: v1
kind: Service
metadata:
  name: nats-svc
spec:
  selector:
    app: nats
  ports:
    - name: nats-client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: nats-monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222